name: SRMIC RTL CI Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build_and_verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup OSS CAD Suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
          python-override: true

    - name: Run Verilator Lint
      run: make lint

    - name: Run Simulation
      run: make sim

    - name: Run Synthesis Sanity
      run: make synth

    - name: Run Formal Verification
      run: make formal
